added extra tests for server with text in and XML out. The results are NOT ok! (https://github.com/LanguageMachines/frog/issues/84)

diff --git a/testserverxml b/testserverxml
--- a/testserverxml
+++ b/testserverxml
@@ -92,3 +92,50 @@ cat testserver4.out >> testserverxml.out
 
 kill $pid
 wait $pid
+
+$frog_bin/frog -X --KANON --skip=p -S 7000  > testserverxml-3.log 2>&1  &
+pid=`echo $!`
+
+if [ `uname` = Darwin ]
+then
+    sleep 30
+else
+    count="0"
+    stat="0"
+
+    while [ $stat -ne 1 ]
+    do
+	#       echo `lsof -i :7000 |grep -c LISTEN`
+	stat=`lsof -i :7000 |grep -c LISTEN`
+	#    echo count=$count
+	#    echo status=$stat
+	count=$((count+1))
+	if [ $count -ge 20 ]; then
+	    echo "unable to start server in time..."
+	    exit 1
+	fi
+	sleep 1
+    done
+fi
+
+\rm  testserver6.out
+\rm  testserver7.out
+
+./frogclient6 &
+pids3[0]=$!
+./frogclient7 &
+pids3[1]=$!
+
+echo "created PID's: ${pids3[*]}"
+for sub_pid in ${pids3[*]}
+do
+    wait $sub_pid
+done
+
+echo "done waiting"
+
+cat testserver6.out >> testserverxml.out
+cat testserver7.out >> testserverxml.out
+
+kill $pid
+wait $pid
