adapted server scripts to check for availability of the service

diff --git a/testserver b/testserver
--- a/testserver
+++ b/testserver
@@ -1,9 +1,24 @@
-#!/bin/sh
+#!/bin/sh -x
 
 $frog_bin/frog -S 7000  > testserver.log 2>&1  &
 pid=`echo $!`
 
-sleep 15
+count="0"
+stat="0"
+while [ $stat -ne 1 ]
+do
+    echo `lsof -i :7000 |grep -c LISTEN`
+    stat=`lsof -i :7000 |grep -c LISTEN`
+    echo count=$count
+    echo status=$stat
+    count=$((count+1))
+    if [ $count -ge 20 ]; then
+	echo "unable to start server in time..."
+	exit 1
+    fi
+    sleep 1
+done
+
 
 ./frogclient5 &
 ./frogclient6 &
diff --git a/testserver-n b/testserver-n
--- a/testserver-n
+++ b/testserver-n
@@ -1,15 +1,28 @@
 #!/bin/sh -x
-
-
 $frog_bin/frog  --keep-parser-files -n -S 7000  > testserver-n.log 2>&1  &
 pid=`echo $!`
 
-sleep 12
+count="0"
+stat="0"
+while [ $stat -ne 1 ]
+do
+#    echo `lsof -i :7000 |grep -c LISTEN`
+    stat=`lsof -i :7000 |grep -c LISTEN`
+#    echo count=$count
+#    echo status=$stat
+    count=$((count+1))
+    if [ $count -ge 20 ]; then
+	echo "unable to start server in time..."
+	exit 1
+    fi
+    sleep 1
+done
 
 ./frogclient1 &
 ./frogclient2 &
 
-sleep 4
+sleep 5
+
 cat testserver1.out > testserver-n.out
 cat testserver2.out >> testserver-n.out
 
diff --git a/testserverxml b/testserverxml
--- a/testserverxml
+++ b/testserverxml
@@ -4,14 +4,30 @@
 $frog_bin/frog -x --skip=p -S 7000  > testserverxml.log 2>&1  &
 pid=`echo $!`
 
+count="0"
+stat="0"
+
+while [ $stat -ne 1 ]
+do
+#    echo `lsof -i :7000 |grep -c LISTEN`
+    stat=`lsof -i :7000 |grep -c LISTEN`
+#    echo count=$count
+#    echo status=$stat
+    count=$((count+1))
+    if [ $count -ge 20 ]; then
+	echo "unable to start server in time..."
+	exit 1
+    fi
+    sleep 1
+done
+
 \rm  testserver3.out
 \rm  testserver4.out
-sleep 10
 
 ./frogclient3 &
 ./frogclient4 &
 
-sleep 3
+sleep 5
 cat testserver3.out > testserverxml.out
 cat testserver4.out >> testserverxml.out
 
@@ -21,14 +37,30 @@ sleep 5
 $frog_bin/frog -x -X --KANON --skip=p -S 7000  >> testserverxml.log 2>&1  &
 pid=`echo $!`
 
+count="0"
+stat="0"
+
+while [ $stat -ne 1 ]
+do
+#    echo `lsof -i :7000 |grep -c LISTEN`
+    stat=`lsof -i :7000 |grep -c LISTEN`
+#    echo count=$count
+#    echo status=$stat
+    count=$((count+1))
+    if [ $count -ge 20 ]; then
+	echo "unable to start server in time..."
+	exit 1
+    fi
+    sleep 1
+done
+
 \rm  testserver3.out
 \rm  testserver4.out
-sleep 10
 
 ./frogclient3 &
 ./frogclient4 &
 
-sleep 3
+sleep 5
 cat testserver3.out >> testserverxml.out
 cat testserver4.out >> testserverxml.out
 
