more OSX adaptation

diff --git a/testserverxml b/testserverxml
--- a/testserverxml
+++ b/testserverxml
@@ -3,27 +3,26 @@
 $frog_bin/frog -x --skip=p -S 7000  > testserverxml-1.log 2>&1  &
 pid=`echo $!`
 
-count="0"
-stat="0"
-
-while [ $stat -ne 1 ]
-do
-    if [ `uname` = Darwin ]
-    then
-	stat=`lsof -i :7000 -e /Volumes/VMware\ Shared\ Folders |grep -c LISTEN`
-    else
-#	echo `lsof -i :7000 |grep -c LISTEN`
+if [ `uname` = Darwin ]
+then
+    sleep 30
+else
+    count="0"
+    stat="0"
+    while [ $stat -ne 1 ]
+    do
+	#	echo `lsof -i :7000 |grep -c LISTEN`
 	stat=`lsof -i :7000 |grep -c LISTEN`
-    fi
-    echo count=$count
-    echo status=$stat
-    count=$((count+1))
-    if [ $count -ge 20 ]; then
-	echo "unable to start server in time..."
-	exit 1
-    fi
-    sleep 1
-done
+	echo count=$count
+	echo status=$stat
+	count=$((count+1))
+	if [ $count -ge 20 ]; then
+	    echo "unable to start server in time..."
+	    exit 1
+	fi
+	sleep 1
+    done
+fi
 
 \rm  testserver3.out
 \rm  testserver4.out
@@ -50,27 +49,27 @@ wait $pid
 $frog_bin/frog -x -X --KANON --skip=p -S 7000  > testserverxml-2.log 2>&1  &
 pid=`echo $!`
 
-count="0"
-stat="0"
+if [ `uname` = Darwin ]
+then
+    sleep 30
+else
+    count="0"
+    stat="0"
 
-while [ $stat -ne 1 ]
-do
-    if [ `uname` = Darwin ]
-    then
-	stat=`lsof -i :7000 -e /Volumes/VMware\ Shared\ Folders |grep -c LISTEN`
-    else
-#       echo `lsof -i :7000 |grep -c LISTEN`
+    while [ $stat -ne 1 ]
+    do
+	#       echo `lsof -i :7000 |grep -c LISTEN`
 	stat=`lsof -i :7000 |grep -c LISTEN`
-    fi
-#    echo count=$count
-#    echo status=$stat
-    count=$((count+1))
-    if [ $count -ge 20 ]; then
-	echo "unable to start server in time..."
-	exit 1
-    fi
-    sleep 1
-done
+	#    echo count=$count
+	#    echo status=$stat
+	count=$((count+1))
+	if [ $count -ge 20 ]; then
+	    echo "unable to start server in time..."
+	    exit 1
+	fi
+	sleep 1
+    done
+fi
 
 \rm  testserver3.out
 \rm  testserver4.out
